name: myfirst
#to push anything to this branch
on: 
  push:
   branches:
    - main
    - dev
  pull_request:
   branches:
    - main
    # - dev
jobs:
  unit-tests:
    name: running unit test
    runs-on: ubuntu-slim
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0
      - name: setup python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run:  |
          mkdir reports/
          pytest --junitxml=reports/unit-test-results.xml --cov=./ --cov-report=xml:reports/coverage.xml  --cov-report=term-missing -v
      - name: upload code coverage report
        uses: actions/upload-artifact@v5.0.0
        with:
          name: unit-test-report
          path: reports/     
  codeql:
      name: codeQl security scan
      runs-on: ubuntu-slim
      permissions:
        contents: read
        actions: read
        security-events: write
      strategy:
        matrix:  
          language: [ 'python']
      steps:
        - name: checkout code
          uses: actions/checkout@v5.0.0

        - name: initialize codeql
          uses: github/codeql-action/init@v3
          with:
            languages: ${{ matrix.language }}

        - name: perform codeql analysis
          uses: github/codeql-action/analyze@v3
          with:
            category: 'security'

  sonarqube:
    name: SonarQube
    needs: unit-tests
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5.0.0 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: download code coverage report
        uses: actions/download-artifact@v5.0.0
        with:
          name: unit-test-report
          path: reports/
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build and push Docker image
    needs: [sonarqube, codeql]
    runs-on: ubuntu-slim
    if: success()
    outputs:
      image-tag: ${{ steps.vars.outputs.IMAGE_TAG }}
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: generate image tags
        id: vars
        run: |
             IMAGE_TAG="${{ github.run_id }}-${{ GITHUB_SHA::7 }}"
             echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Build Image (no push)
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: my-first-app:${{ steps.vars.outputs.IMAGE_TAG }}
      - name: save docker image as artifact
        run: docker save image my-first-app:${{ steps.vars.outputs.IMAGE_TAG }} -o my-first-app.tar
      - name: upload docker image artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: docker-image
          path: my-first-app.tar