name: myfirst
#to push anything to this branch
on: 
  push:
   branches:
    - main
    - dev
  pull_request:
   branches:
    - main
    # - dev

jobs:
 job1:
   name: JOB1
   runs-on: ubuntu-slim
   steps:
     - name: checking the current directory
       run: |
          pwd
          ls -lrt
          hostname
     - name: checkout
       uses: actions/checkout@v5.0.0
     - name: step-3
       run: |
         echo `pwd` >> myartifact.txt
         mkdir artifacts
         echo `ls -lrt` >> artifacts/list.txt
         echo `hostname` >> artifacts/hostname.txt
     - name: upload-artifact
       uses: actions/upload-artifact@v5.0.0
       with:
         name: single_file
         path: ./myartifact.txt
     - name: upload from directory
       uses: actions/upload-artifact@v5.0.0
       with:
         name: directory_artifacts
         path: artifacts/
     - name: upload from multiple paths with exclusions
       uses: actions/upload-artifact@v5.0.0
       with:
          name: multiple_paths_with_exclusions
          path: |
            ./myartifact.txt
            artifacts/
            !**/hostname.txt
 job2:
  name: JOB2
  needs: job1
  runs-on: ubuntu-slim
  steps:
     - name: checking the current directory
       run: |
          pwd
          ls -lrt
     - name: download-artifact
       uses: actions/download-artifact@v5.0.0
       with:
         name: single_file  
     - name: checking current directory post downlaod
       run: |
         pwd
         ls -lrt
     - name: for PR demo
       run: exit 1


 job3:
  name: JOB3
  needs: job1
  runs-on: ubuntu-slim
  steps:
     - name: checking the current directory
       run: |
          pwd
          ls -lrt
     - name: download-directory
       uses: actions/download-artifact@v5.0.0
       with:
         name: directory_artifacts
     - name: checking current directory post downlaod
       run: |
         pwd
         ls -lrt

 job4:
  name: JOB4
  needs: job1
  runs-on: ubuntu-slim
  steps:
     - name: checking custom folder for download
       run: |
          mkdir -p single_file
          mkdir -p download_directory
     - name: checking the current directory
       run: |
          pwd
          ls -lrt 
     - name: Download single file artifact
       uses: actions/download-artifact@v5.0.0
       with:
         name: single_file
         path: single_file

     - name: Download directory artifact
       uses: actions/download-artifact@v5.0.0
       with:
          name: directory_artifacts
          path: download_directory
     - name: checking current directory post downlaod
       run: |
         pwd
         echo "single file content"
         ls -lrt single_file
         echo "checking directory artifact content"
         ls -lrt download_directory
